# Generated by Django 3.1.5 on 2021-01-20 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210116_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='content',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 5, 31, 56, 37836, tzinfo=utc)),
        ),
    ]
